language: generic 
sudo: required
services:
  -docker

before_install:
  -docker build -t mettumanu/docker-react -f dockerfile.dev .
script:
  - docker run -e CI=true mettumanu/docker-react npm run test
