language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t mettumanu/docker-react -f dockerfile.dev .
script:
  - docker run -e CI=true mettumanu/docker-react npm run test


deploy:

  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "https://s3.console.aws.amazon.com/s3/#"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secet_access_key:
    secure: $AWS_SECRET_KEY
